
server:
  port: 8082

spring:
  application:
    name: hotelService
  data:
    mongodb:
      uri: mongodb://localhost:27017/hotel_db

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080
